################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../DSPLib/source/vector/msp_abs_iq31.c \
../DSPLib/source/vector/msp_abs_q15.c \
../DSPLib/source/vector/msp_add_iq31.c \
../DSPLib/source/vector/msp_add_q15.c \
../DSPLib/source/vector/msp_cmplx_add_iq31.c \
../DSPLib/source/vector/msp_cmplx_add_q15.c \
../DSPLib/source/vector/msp_cmplx_conj_iq31.c \
../DSPLib/source/vector/msp_cmplx_conj_q15.c \
../DSPLib/source/vector/msp_cmplx_mac_iq31.c \
../DSPLib/source/vector/msp_cmplx_mac_q15.c \
../DSPLib/source/vector/msp_cmplx_mpy_iq31.c \
../DSPLib/source/vector/msp_cmplx_mpy_q15.c \
../DSPLib/source/vector/msp_cmplx_mpy_real_iq31.c \
../DSPLib/source/vector/msp_cmplx_mpy_real_q15.c \
../DSPLib/source/vector/msp_cmplx_scale_iq31.c \
../DSPLib/source/vector/msp_cmplx_scale_q15.c \
../DSPLib/source/vector/msp_cmplx_shift_iq31.c \
../DSPLib/source/vector/msp_cmplx_shift_q15.c \
../DSPLib/source/vector/msp_cmplx_sub_iq31.c \
../DSPLib/source/vector/msp_cmplx_sub_q15.c \
../DSPLib/source/vector/msp_mac_iq31.c \
../DSPLib/source/vector/msp_mac_q15.c \
../DSPLib/source/vector/msp_max_iq31.c \
../DSPLib/source/vector/msp_max_q15.c \
../DSPLib/source/vector/msp_max_uq15.c \
../DSPLib/source/vector/msp_max_uq31.c \
../DSPLib/source/vector/msp_min_iq31.c \
../DSPLib/source/vector/msp_min_q15.c \
../DSPLib/source/vector/msp_min_uq15.c \
../DSPLib/source/vector/msp_min_uq31.c \
../DSPLib/source/vector/msp_mpy_iq31.c \
../DSPLib/source/vector/msp_mpy_q15.c \
../DSPLib/source/vector/msp_neg_iq31.c \
../DSPLib/source/vector/msp_neg_q15.c \
../DSPLib/source/vector/msp_offset_iq31.c \
../DSPLib/source/vector/msp_offset_q15.c \
../DSPLib/source/vector/msp_scale_iq31.c \
../DSPLib/source/vector/msp_scale_q15.c \
../DSPLib/source/vector/msp_shift_iq31.c \
../DSPLib/source/vector/msp_shift_q15.c \
../DSPLib/source/vector/msp_sub_iq31.c \
../DSPLib/source/vector/msp_sub_q15.c 

C_DEPS += \
./DSPLib/source/vector/msp_abs_iq31.d \
./DSPLib/source/vector/msp_abs_q15.d \
./DSPLib/source/vector/msp_add_iq31.d \
./DSPLib/source/vector/msp_add_q15.d \
./DSPLib/source/vector/msp_cmplx_add_iq31.d \
./DSPLib/source/vector/msp_cmplx_add_q15.d \
./DSPLib/source/vector/msp_cmplx_conj_iq31.d \
./DSPLib/source/vector/msp_cmplx_conj_q15.d \
./DSPLib/source/vector/msp_cmplx_mac_iq31.d \
./DSPLib/source/vector/msp_cmplx_mac_q15.d \
./DSPLib/source/vector/msp_cmplx_mpy_iq31.d \
./DSPLib/source/vector/msp_cmplx_mpy_q15.d \
./DSPLib/source/vector/msp_cmplx_mpy_real_iq31.d \
./DSPLib/source/vector/msp_cmplx_mpy_real_q15.d \
./DSPLib/source/vector/msp_cmplx_scale_iq31.d \
./DSPLib/source/vector/msp_cmplx_scale_q15.d \
./DSPLib/source/vector/msp_cmplx_shift_iq31.d \
./DSPLib/source/vector/msp_cmplx_shift_q15.d \
./DSPLib/source/vector/msp_cmplx_sub_iq31.d \
./DSPLib/source/vector/msp_cmplx_sub_q15.d \
./DSPLib/source/vector/msp_mac_iq31.d \
./DSPLib/source/vector/msp_mac_q15.d \
./DSPLib/source/vector/msp_max_iq31.d \
./DSPLib/source/vector/msp_max_q15.d \
./DSPLib/source/vector/msp_max_uq15.d \
./DSPLib/source/vector/msp_max_uq31.d \
./DSPLib/source/vector/msp_min_iq31.d \
./DSPLib/source/vector/msp_min_q15.d \
./DSPLib/source/vector/msp_min_uq15.d \
./DSPLib/source/vector/msp_min_uq31.d \
./DSPLib/source/vector/msp_mpy_iq31.d \
./DSPLib/source/vector/msp_mpy_q15.d \
./DSPLib/source/vector/msp_neg_iq31.d \
./DSPLib/source/vector/msp_neg_q15.d \
./DSPLib/source/vector/msp_offset_iq31.d \
./DSPLib/source/vector/msp_offset_q15.d \
./DSPLib/source/vector/msp_scale_iq31.d \
./DSPLib/source/vector/msp_scale_q15.d \
./DSPLib/source/vector/msp_shift_iq31.d \
./DSPLib/source/vector/msp_shift_q15.d \
./DSPLib/source/vector/msp_sub_iq31.d \
./DSPLib/source/vector/msp_sub_q15.d 

OBJS += \
./DSPLib/source/vector/msp_abs_iq31.obj \
./DSPLib/source/vector/msp_abs_q15.obj \
./DSPLib/source/vector/msp_add_iq31.obj \
./DSPLib/source/vector/msp_add_q15.obj \
./DSPLib/source/vector/msp_cmplx_add_iq31.obj \
./DSPLib/source/vector/msp_cmplx_add_q15.obj \
./DSPLib/source/vector/msp_cmplx_conj_iq31.obj \
./DSPLib/source/vector/msp_cmplx_conj_q15.obj \
./DSPLib/source/vector/msp_cmplx_mac_iq31.obj \
./DSPLib/source/vector/msp_cmplx_mac_q15.obj \
./DSPLib/source/vector/msp_cmplx_mpy_iq31.obj \
./DSPLib/source/vector/msp_cmplx_mpy_q15.obj \
./DSPLib/source/vector/msp_cmplx_mpy_real_iq31.obj \
./DSPLib/source/vector/msp_cmplx_mpy_real_q15.obj \
./DSPLib/source/vector/msp_cmplx_scale_iq31.obj \
./DSPLib/source/vector/msp_cmplx_scale_q15.obj \
./DSPLib/source/vector/msp_cmplx_shift_iq31.obj \
./DSPLib/source/vector/msp_cmplx_shift_q15.obj \
./DSPLib/source/vector/msp_cmplx_sub_iq31.obj \
./DSPLib/source/vector/msp_cmplx_sub_q15.obj \
./DSPLib/source/vector/msp_mac_iq31.obj \
./DSPLib/source/vector/msp_mac_q15.obj \
./DSPLib/source/vector/msp_max_iq31.obj \
./DSPLib/source/vector/msp_max_q15.obj \
./DSPLib/source/vector/msp_max_uq15.obj \
./DSPLib/source/vector/msp_max_uq31.obj \
./DSPLib/source/vector/msp_min_iq31.obj \
./DSPLib/source/vector/msp_min_q15.obj \
./DSPLib/source/vector/msp_min_uq15.obj \
./DSPLib/source/vector/msp_min_uq31.obj \
./DSPLib/source/vector/msp_mpy_iq31.obj \
./DSPLib/source/vector/msp_mpy_q15.obj \
./DSPLib/source/vector/msp_neg_iq31.obj \
./DSPLib/source/vector/msp_neg_q15.obj \
./DSPLib/source/vector/msp_offset_iq31.obj \
./DSPLib/source/vector/msp_offset_q15.obj \
./DSPLib/source/vector/msp_scale_iq31.obj \
./DSPLib/source/vector/msp_scale_q15.obj \
./DSPLib/source/vector/msp_shift_iq31.obj \
./DSPLib/source/vector/msp_shift_q15.obj \
./DSPLib/source/vector/msp_sub_iq31.obj \
./DSPLib/source/vector/msp_sub_q15.obj 

OBJS__QUOTED += \
"DSPLib\source\vector\msp_abs_iq31.obj" \
"DSPLib\source\vector\msp_abs_q15.obj" \
"DSPLib\source\vector\msp_add_iq31.obj" \
"DSPLib\source\vector\msp_add_q15.obj" \
"DSPLib\source\vector\msp_cmplx_add_iq31.obj" \
"DSPLib\source\vector\msp_cmplx_add_q15.obj" \
"DSPLib\source\vector\msp_cmplx_conj_iq31.obj" \
"DSPLib\source\vector\msp_cmplx_conj_q15.obj" \
"DSPLib\source\vector\msp_cmplx_mac_iq31.obj" \
"DSPLib\source\vector\msp_cmplx_mac_q15.obj" \
"DSPLib\source\vector\msp_cmplx_mpy_iq31.obj" \
"DSPLib\source\vector\msp_cmplx_mpy_q15.obj" \
"DSPLib\source\vector\msp_cmplx_mpy_real_iq31.obj" \
"DSPLib\source\vector\msp_cmplx_mpy_real_q15.obj" \
"DSPLib\source\vector\msp_cmplx_scale_iq31.obj" \
"DSPLib\source\vector\msp_cmplx_scale_q15.obj" \
"DSPLib\source\vector\msp_cmplx_shift_iq31.obj" \
"DSPLib\source\vector\msp_cmplx_shift_q15.obj" \
"DSPLib\source\vector\msp_cmplx_sub_iq31.obj" \
"DSPLib\source\vector\msp_cmplx_sub_q15.obj" \
"DSPLib\source\vector\msp_mac_iq31.obj" \
"DSPLib\source\vector\msp_mac_q15.obj" \
"DSPLib\source\vector\msp_max_iq31.obj" \
"DSPLib\source\vector\msp_max_q15.obj" \
"DSPLib\source\vector\msp_max_uq15.obj" \
"DSPLib\source\vector\msp_max_uq31.obj" \
"DSPLib\source\vector\msp_min_iq31.obj" \
"DSPLib\source\vector\msp_min_q15.obj" \
"DSPLib\source\vector\msp_min_uq15.obj" \
"DSPLib\source\vector\msp_min_uq31.obj" \
"DSPLib\source\vector\msp_mpy_iq31.obj" \
"DSPLib\source\vector\msp_mpy_q15.obj" \
"DSPLib\source\vector\msp_neg_iq31.obj" \
"DSPLib\source\vector\msp_neg_q15.obj" \
"DSPLib\source\vector\msp_offset_iq31.obj" \
"DSPLib\source\vector\msp_offset_q15.obj" \
"DSPLib\source\vector\msp_scale_iq31.obj" \
"DSPLib\source\vector\msp_scale_q15.obj" \
"DSPLib\source\vector\msp_shift_iq31.obj" \
"DSPLib\source\vector\msp_shift_q15.obj" \
"DSPLib\source\vector\msp_sub_iq31.obj" \
"DSPLib\source\vector\msp_sub_q15.obj" 

C_DEPS__QUOTED += \
"DSPLib\source\vector\msp_abs_iq31.d" \
"DSPLib\source\vector\msp_abs_q15.d" \
"DSPLib\source\vector\msp_add_iq31.d" \
"DSPLib\source\vector\msp_add_q15.d" \
"DSPLib\source\vector\msp_cmplx_add_iq31.d" \
"DSPLib\source\vector\msp_cmplx_add_q15.d" \
"DSPLib\source\vector\msp_cmplx_conj_iq31.d" \
"DSPLib\source\vector\msp_cmplx_conj_q15.d" \
"DSPLib\source\vector\msp_cmplx_mac_iq31.d" \
"DSPLib\source\vector\msp_cmplx_mac_q15.d" \
"DSPLib\source\vector\msp_cmplx_mpy_iq31.d" \
"DSPLib\source\vector\msp_cmplx_mpy_q15.d" \
"DSPLib\source\vector\msp_cmplx_mpy_real_iq31.d" \
"DSPLib\source\vector\msp_cmplx_mpy_real_q15.d" \
"DSPLib\source\vector\msp_cmplx_scale_iq31.d" \
"DSPLib\source\vector\msp_cmplx_scale_q15.d" \
"DSPLib\source\vector\msp_cmplx_shift_iq31.d" \
"DSPLib\source\vector\msp_cmplx_shift_q15.d" \
"DSPLib\source\vector\msp_cmplx_sub_iq31.d" \
"DSPLib\source\vector\msp_cmplx_sub_q15.d" \
"DSPLib\source\vector\msp_mac_iq31.d" \
"DSPLib\source\vector\msp_mac_q15.d" \
"DSPLib\source\vector\msp_max_iq31.d" \
"DSPLib\source\vector\msp_max_q15.d" \
"DSPLib\source\vector\msp_max_uq15.d" \
"DSPLib\source\vector\msp_max_uq31.d" \
"DSPLib\source\vector\msp_min_iq31.d" \
"DSPLib\source\vector\msp_min_q15.d" \
"DSPLib\source\vector\msp_min_uq15.d" \
"DSPLib\source\vector\msp_min_uq31.d" \
"DSPLib\source\vector\msp_mpy_iq31.d" \
"DSPLib\source\vector\msp_mpy_q15.d" \
"DSPLib\source\vector\msp_neg_iq31.d" \
"DSPLib\source\vector\msp_neg_q15.d" \
"DSPLib\source\vector\msp_offset_iq31.d" \
"DSPLib\source\vector\msp_offset_q15.d" \
"DSPLib\source\vector\msp_scale_iq31.d" \
"DSPLib\source\vector\msp_scale_q15.d" \
"DSPLib\source\vector\msp_shift_iq31.d" \
"DSPLib\source\vector\msp_shift_q15.d" \
"DSPLib\source\vector\msp_sub_iq31.d" \
"DSPLib\source\vector\msp_sub_q15.d" 

C_SRCS__QUOTED += \
"../DSPLib/source/vector/msp_abs_iq31.c" \
"../DSPLib/source/vector/msp_abs_q15.c" \
"../DSPLib/source/vector/msp_add_iq31.c" \
"../DSPLib/source/vector/msp_add_q15.c" \
"../DSPLib/source/vector/msp_cmplx_add_iq31.c" \
"../DSPLib/source/vector/msp_cmplx_add_q15.c" \
"../DSPLib/source/vector/msp_cmplx_conj_iq31.c" \
"../DSPLib/source/vector/msp_cmplx_conj_q15.c" \
"../DSPLib/source/vector/msp_cmplx_mac_iq31.c" \
"../DSPLib/source/vector/msp_cmplx_mac_q15.c" \
"../DSPLib/source/vector/msp_cmplx_mpy_iq31.c" \
"../DSPLib/source/vector/msp_cmplx_mpy_q15.c" \
"../DSPLib/source/vector/msp_cmplx_mpy_real_iq31.c" \
"../DSPLib/source/vector/msp_cmplx_mpy_real_q15.c" \
"../DSPLib/source/vector/msp_cmplx_scale_iq31.c" \
"../DSPLib/source/vector/msp_cmplx_scale_q15.c" \
"../DSPLib/source/vector/msp_cmplx_shift_iq31.c" \
"../DSPLib/source/vector/msp_cmplx_shift_q15.c" \
"../DSPLib/source/vector/msp_cmplx_sub_iq31.c" \
"../DSPLib/source/vector/msp_cmplx_sub_q15.c" \
"../DSPLib/source/vector/msp_mac_iq31.c" \
"../DSPLib/source/vector/msp_mac_q15.c" \
"../DSPLib/source/vector/msp_max_iq31.c" \
"../DSPLib/source/vector/msp_max_q15.c" \
"../DSPLib/source/vector/msp_max_uq15.c" \
"../DSPLib/source/vector/msp_max_uq31.c" \
"../DSPLib/source/vector/msp_min_iq31.c" \
"../DSPLib/source/vector/msp_min_q15.c" \
"../DSPLib/source/vector/msp_min_uq15.c" \
"../DSPLib/source/vector/msp_min_uq31.c" \
"../DSPLib/source/vector/msp_mpy_iq31.c" \
"../DSPLib/source/vector/msp_mpy_q15.c" \
"../DSPLib/source/vector/msp_neg_iq31.c" \
"../DSPLib/source/vector/msp_neg_q15.c" \
"../DSPLib/source/vector/msp_offset_iq31.c" \
"../DSPLib/source/vector/msp_offset_q15.c" \
"../DSPLib/source/vector/msp_scale_iq31.c" \
"../DSPLib/source/vector/msp_scale_q15.c" \
"../DSPLib/source/vector/msp_shift_iq31.c" \
"../DSPLib/source/vector/msp_shift_q15.c" \
"../DSPLib/source/vector/msp_sub_iq31.c" \
"../DSPLib/source/vector/msp_sub_q15.c" 


